### ISSUE TITLE
Implement Google Login for View

### ISSUE THREAD

**Issue by jorgelandaverde** [shpe/headcount#3]
feature is needed to make api calls to Google Drive

**Comment by Abuitime** [comment]
Got it boss!


*Alejandro M. Buitimea (Alex)*
University of California, San Diego *|* Computer Engineering
Society of Hispanic Professional Engineers *|* UC San Diego Chapter
President
alex.buitimea@gmail.com *|* 818.935.9355 *|* abuitime@ucsd.edu

*Working hard and working smart sometimes can be two different things*

**Comment by Abuitime** [comment]
Done
